#!/bin/sh
# Call Jenkins to start build and pass environment parameter
#
echo "executing post-receive hook"
echo "environment=testing"
echo "user=root"

# cURL POST request using jenkins user with API token
curl -u root:114664d5fc89317f52a33768ba6e105b2d \
    --data "delay=0sec&environment=testing" \
    "http://localhost:8080/job/goSecurity/buildWithParameters"